### ISSUE TITLE
AttributeError: conv2d is not available with Keras 3.

### ISSUE THREAD

**Issue by flybirdxx** [ralonsobeas/ComfyUI-HDRConversion#5]
`!!! Exception during processing !!! `conv2d` is not available with Keras 3.
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfyui\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfyui\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\comfyui\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfyui\ComfyUI\custom_nodes\ComfyUI-HDRConversion\nodes\nodes.py", line 85, in to_hdr
    dequantize_and_linearize_run("ComfyUI/custom_nodes/ComfyUI-HDRConversion/IntrinsicHDR/tmp", root)
  File "E:\comfyui\ComfyUI\custom_nodes\ComfyUI-HDRConversion\IntrinsicHDR\dequantize_and_linearize.py", line 201, in dequantize_and_linearize_run
    lin_graph = build_graph(ldr, is_training)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfyui\ComfyUI\custom_nodes\ComfyUI-HDRConversion\IntrinsicHDR\dequantize_and_linearize.py", line 41, in build_graph
    C_pred = _clip(dequantization_model.inference(ldr))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfyui\ComfyUI\custom_nodes\ComfyUI-HDRConversion\IntrinsicHDR\baselines\SingleHDR\dequantization_net.py", line 12, in inference
    return self._build_model(input_images)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\comfyui\ComfyUI\custom_nodes\ComfyUI-HDRConversion\IntrinsicHDR\baselines\SingleHDR\dequantization_net.py", line 35, in _build_model
    x = tf.nn.leaky_relu(tf.layers.conv2d(input_images, 16, 7, 1, 'same'), 0.1)
                         ^^^^^^^^^^^^^^^^
  File "E:\comfyui\python_embeded\Lib\site-packages\tensorflow\python\util\lazy_loader.py", line 207, in __getattr__
    raise AttributeError(
AttributeError: `conv2d` is not available with Keras 3.`

I encountered the above error in my use, then I modified the code according to GPT
![image](https://github.com/user-attachments/assets/91669b84-db7f-4211-a4f7-45d5f76ce7cf)
And then there's a new problem.
![image](https://github.com/user-attachments/assets/1e079c4e-7b83-407f-a8d3-52d0c318aef6)

**Comment by ralonsobeas** [comment]
Hi! This problem is about packages version. Ill try to fix it as soon as possible

**Comment by subhansu7119** [comment]
resolved ? if yes please provide solution
